OPENING_PROMPT :: #string DONE
Cutscene
DONE;

TREE_TALK :: #string DONE
Tree.
DONE

SIREN_TALK :: #string DONE
blah blah blah
DONE

/*
I am writing game stuff here

aos : *while lying down* if you try talking to her, she say "pst .. hold my hands"

Then the hold hands option appears

when you interact with someone, you see a prompt and then you can pick what you want

I am thinking in the real beginning, you follow the beam and when you find her, she tells you how happy she is. how absolutely happy and then you zone out and when you zone in, the "past .. hold my hands part" starts
*/